=== LuizZak/SwiftAnimGen/animations.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "$ref": "#/definitions/Animations",
    "definitions": {
        "Animations": {
            "type": "object",
            "description": "A definition file for animations.json file.",
            "additionalProperties": false,
            "properties": {
                "class_name": {
                    "type": "string",
                    "description": "The name of the class to generate."
                },
                "superclass": {
                    "type": "string",
                    "description": "The name of the superclass to extend. If not present, defaults to 'AnimationStateMachine'."
                },
                "options": {
                    "$ref": "#/definitions/GlobalOptions"
                },
                "constants": {
                    "$ref": "#/definitions/Constants"
                },
                "entry_points": {
                    "$ref": "#/definitions/EntryPoints"
                },
                "states": {
                    "$ref": "#/definitions/States"
                }
            },
            "required": [
                "class_name",
                "states"
            ]
        },
        "GlobalOptions": {
            "type": "object",
            "description": "Global options for generated scripts.",
            "additionalProperties": false,
            "properties": {
                "animation_name_kind": {
                    "enum": [
                        "constant"
                    ]
                }
            }
        },
        "Constants": {
            "type": "object",
            "description": "Describes a set of constants for animations.json file.",
            "additionalProperties": false,
            "properties": {
                "state_machine": {
                    "$ref": "#/definitions/StateMachineConstantContainer",
                    "description": "State machine constants that will be unfolded as 'state_machine.parameters[CONSTANT_NAME]' automatically in generated code."
                },
                "animation_names": {
                    "$ref": "#/definitions/ConstantsContainer",
                    "description": "Constants pertaining to the animation names."
                }
            }
        },
        "StateMachineConstantContainer": {
            "type": "array",
            "description": "An array of state machine constants that will be visible by the generated script.",
            "items": {
                "type": "object",
                "description": "A state machine constant entry.",
                "additionalProperties": false,
                "properties": {
                    "constant": {
                        "$ref": "#/definitions/Constant"
                    },
                    "type": {
                        "type": "string",
                        "description": "The static type of the constant. Affects generated setters for the constant definition."
                    },
                    "setter_name": {
                        "type": "string",
                        "description": "A valid GDScript function name to use as a setter for this constant."
                    }
                },
                "required": [
                    "constant",
                    "type"
                ]
            }
        },
        "ConstantsContainer": {
            "type": "array",
            "description": "An array of constants that will be visible by the generated script.",
            "items": {
                "$ref": "#/definitions/Constant"
            }
        },
        "Constant": {
            "type": "object",
            "description": "A constant that will be visible by the generated script. Expected to be a dictionary with a single key: pair entry."
        },
        "EntryPoints": {
            "type": "array",
            "description": "A list of entry point definitions.",
            "items": {
                "$ref": "#/definitions/EntryPointDefinition"
            }
        },
        "EntryPointDefinition": {
            "type": "object",
            "description": "A reference to an animation state that will be made an entry point as a function definition."
        },
        "States": {
            "type": "array",
            "description": "An array of state definitions.",
            "items": {
                "$ref": "#/definitions/State"
            }
        },
        "State": {
            "type": "object",
            "description": "A state definition.",
            "additionalProperties": false,
            "properties": {
                "name": {
                    "type": "string",
                    "description": "The name for this state."
                },
                "description": {
                    "type": "string",
                    "description": "An optional string description that will be generated as a comment for this state's class."
                },
                "animation_name": {
                    "type": "string",
                    "description": "The name of the animation that this state plays. Must be an animation name defined in constants.animation_names."
                },
                "transitions": {
                    "type": "array",
                    "description": "An array of state transitions that will be applied instantly according to their conditions.",
                    "items": {
                        "$ref": "#/definitions/Transition"
                    }
                },
                "on_end": {
                    "type": "array",
                    "description": "An array of state transitions that will be applied when the animation finishes playback according to their conditions.",
                    "items": {
                        "$ref": "#/definitions/Transition"
                    }
                }
            },
            "required": [
                "name",
                "animation_name"
            ]
        },
        "Transition": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "state": {
                    "type": "string",
                    "description": "The name of the state to transition to."
                },
                "conditions": {
                    "type": "string",
                    "description": "A GDScript conditional expression that will be checked before the transition is applied. Constants that match ones in 'constants.state_machine' within are automatically expanded to 'state_machine.parameters[CONSTANT_NAME]'."
                },
                "options": {
                    "type": "object",
                    "description": "Optional options to apply to the transition.",
                    "additionalProperties": false,
                    "properties": {
                        "initializer": {
                            "type": "string",
                            "description": "A replacement to the usual '.new()' appended to the state transition. Can be used to apply custom parameters to the state's initializer, such as '.new(animations.current_animation_position)' for playing the next state at the same position as this state's current position."
                        }
                    }
                }
            },
            "required": [
                "state"
            ]
        }
    }
}

=== LuizZak/SwiftAnimGen/example.json
{
    "class_name": "ExampleAnimationStateMachine",
    "options": {
        "animation_name_kind": "constant"
    },
    "constants": {
        "state_machine": [
            { "constant": { "SM_CROUCHING": "crouching" }, "type": "bool", "setter_name": "set_crouching" },
            { "constant": { "SM_WALKING": "walking" }, "type": "bool", "setter_name": "set_walking" },
            { "constant": { "SM_ON_AIR": "on_air" }, "type": "bool", "setter_name": "set_on_air" }
        ],
        "animation_names": [
            { "ANIM_IDLE": "idle" },
            { "ANIM_CROUCH": "crouch" },
            { "ANIM_RUN": "run" },
            { "ANIM_JUMP": "jump" }
        ]
    },
    "entry_points": [
        { "name": "IdleState" },
        { "name": "CrouchState" },
        { "name": "RunState" },
        { "name": "JumpState" }
    ],
    "states": [
        {
            "name": "IdleState",
            "description": "Idle, not running",
            "animation_name": "ANIM_IDLE",
            "transitions": [
                { "state": "RunState", "conditions": "SM_WALKING" },
                { "state": "CrouchState", "conditions": "SM_CROUCHING" }
            ]
        },
        {
            "name": "CrouchState",
            "description": "Crouching, not running",
            "animation_name": "ANIM_CROUCH",
            "transitions": [
                { "state": "IdleState", "conditions": "not SM_CROUCHING" }
            ]
        },
        {
            "name": "RunState",
            "description": "Run state",
            "animation_name": "ANIM_RUN",
            "transitions": [
                { "state": "IdleState", "conditions": "not SM_WALKING" }
            ]
        },
        {
            "name": "JumpState",
            "description": "On air",
            "animation_name": "ANIM_JUMP",
            "transitions": [
                { "state": "IdleState", "conditions": "not SM_ON_AIR" }
            ],
            "on_end": [
                { "state": "IdleState" }
            ]
        }
    ]
}
